version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 11.5

    environment:
      FASTLANE_LANE: build_and_test
    steps:
      - checkout
      - run: cd src/xcode && bundle install
      - run:
          name: Fastlane
          command: cd src/xcode && bundle exec fastlane $FASTLANE_LANE

workflows:
    default:
        jobs:
          - build-and-test
