version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 11.5.0  # Change to 11.5 once the GM version is available

    steps:
      - checkout
      - run: cd src/xcode && bundle install
      - run:
          name: Build
          command: cd src/xcode && bundle exec fastlane build
# Uncomment after xcode upgrade
#      - run:
#          name: Tests
#          command: cd src/xcode && bundle exec fastlane test

workflows:
    default:
        jobs:
          - build-and-test
